### PR TITLE
Corrected 4x4 binning for v1 camera to 2x2

### PR DESCRIPTION
**Pull request by kozuch**
Datasheet lists only 2x2 binning, see here: http://cdn.sparkfun.com/datasheets/Dev/RaspberryPi/ov5647_full.pdf

### CODE REVIEW

**Comment by 6by9** [comment]
It's 2x2 binning and then 2x2 skipping. Overall the resolution is reduced by 4x4.

**Comment by kozuch** [comment]
Ok, but then the column heading is still misleading.

**Comment by waveform80** [comment]
Feel free to suggest something better, but understand that writing the documentation is a balance between keeping things reasonably simple and being accurate. In other words, I consider the current state acceptable (it specifies the resolution reduction correctly which is all the majority of users care about, because that's what affects the FoV, without leading to follow-up questions like "which are binned and which are skipped?", "does that change with flips?", etc.). That said, if you feel something else would be better (e.g. another callout beneath the table clarifying the meaning of 4x4 binning, or another column in the table specifying skipping), do feel free to update the PR and I'll take a look.

**Comment by kozuch** [comment]
I actually prefer being both simple and accurate at the same time :). Lets put an asterisk (or other sign) as a note to those "4x4"s and explain the truth below. Do you agree with this? If so, I will make the change.

**Comment by waveform80** [comment]
Sure, that sounds fine. Just in case you're not familiar with it: you can edit this PR just by making another commit (don't worry about multiple commits - I can squash them on merge).

**Pull request closed without merging**
