### PR TITLE
Several Improvements/Fixes Listed Below

### PR DESCRIPTION
**Pull request by GeorgeCazenavette**
Edits made with the help of @maxwelljg

Changed PiBayerArray.flush() so that it outputs a 2D array which is used by most entities interested in raw data.  Also, removed the np.delete() function from flush() and instead built a new array from the data, cutting 1.5 seconds off the raw image capture time.

Edited PiBayerArray.demosaic() to work with the 2D array.  Also changed the bayer pattern to the correct pattern.  Previously, the flush and demosaic functions assumed the bayer pattern of the picamera sensor was GBRG when it is actually BGGR.  This resulted in images obtained from the raw data having the incorrect colors.  (Using the demosaic function would still create a correctly colored image since the colors were originally stored in the same incorrect pattern.  Building an image in RGB format from the raw data using the correct pattern (BGGR) would create a miscolored image, however.)

### CODE REVIEW

**Comment by GeorgeCazenavette** [comment]
@waveform80 By the way, we are the people that you were discussing the raw data and syncing with on stack exchange over the past few days.

**Comment by 6by9** [comment]
V1 sensor will produce GBRG by default. V2 produces RGGB. You've just switched from one sensor to the other :-/
However for either of them, adding H or V flips will change the order. Flips are implemented by just reading the sensor array in a different direction.

If you really want to do this properly, then my hacked version of dcraw processes the raw header produced alongside the raw data, and extracts the width, height, and Bayer format correctly. That also would then remove the hard coded widths/heights for reshape & crop in flush, and in theory can then work with ```sensor_mode``` to capture with any of the sensor modes (stills always use the full 5 or 8MP by default). You would need to do a search for the @BRCM string after the JPEG, or have a table of the potential offsets from the end of the file. That was one bit I didn't get around to with the dcraw mods.

**Comment by GeorgeCazenavette** [comment]
@6by9 
After performing extensive tests with both sensors, without implementing any flips, both sensors have a BGGR pattern.  I work in a laboratory that specializes in analyzing raw imagery for the purpose of characterizing cameras.  Performing a spectral response test where images are taken of a monochrometer at 10nm increments in wavelength shows us which pixels respond to which colors of light.  For both sensors, without any flips performed, it was evident that they had a BGGR bayer pattern.  This is just confirming what was already in the documentation: http://picamera.readthedocs.io/en/release-1.10/recipes2.html

**Comment by 6by9** [comment]
@GeorgeCazenavette I have the firmware source code in front of me - that was my reference.

What I had missed was that the OV5647 driver goes and enforces an hflip due to a quirk in the sensor, and the IMX219 driver does both h&v flips to make the image orientation match the OV5647. Nothing like hiding stuff (oh drat, I wrote that code - ahem!).

GBRG + H flip = BGGR
RGGB + H&V flips = BGGR
so you are right that both come out as BGGR if no flips are in force. Apologies.

My point still stands that you can parse the header to read the actual Bayer order for that capture, including accounting for any flips.

**Comment by GeorgeCazenavette** [comment]
@6by9 Ah, well that makes sense.  Sorry for the confusion...  

I would love to look at that and try to implement it.  However, I am going back to school soon, so I will not have access to any of the equipment for a means of testing.  I can try to get it done this week.

Aside from rewriting the bayer pattern, one of the primary fixes I implemented was saving the raw data as a 2D array instead of a 3D array.  The 3D array took up 3 times as much memory due to all the zeros it was storing.  All of the data is still there in the 2D array.  I also did this because most de-bayering algorithms take a 2D array and a bayer pattern as input and return a 3D de-mosaiced array.

Anyway, do you know off-hand how the header for the bayer data is formatted?  As in where would the dimensions of the image and the bayer pattern be found?  Thanks for your help.

**Comment by 6by9** [comment]
Sorry, I thought I'd linked to my dcraw in my first review. It looks like it disappeared.
https://github.com/6by9/RPiTest/blob/master/dcraw/dcraw.c#L7815

**Comment by 6by9** [comment]
BTW I only watch this repo for potential firmware issues. Memory saving on 2D vs 3D arrays sounds great, but not something I'll comment on - @waveform80 will pick that bit up at some point.

**Comment by waveform80** [comment]
@GeorgeCazenavette many thanks for the PR - I'll try and test it out this week. After a quick skim through the code, I will have to make a couple of changes:

> Changed PiBayerArray.flush() so that it outputs a 2D array which is used by most entities interested in raw data

I'm sure it's true that most are interested in a 2D array, but that's still a backwards incompatible change, so it can't go in as is. As a general rule, a new release of picamera must ensure that all existing scripts continue to work without modification unless the major version number changes (indicating backwards incompatible changes). A 2.0 version isn't on the cards yet, so this would need to change slightly.

I'd either make a separate class (PiBayerArray2D?) or add an optional parameter to the constructor to decide the output type. There's a couple of other really minor things to change (`4.0/5` isn't required; the future division import means you can just use `4/5` but given you actually want an int from that anyway, you're better off just doing `(data.shape[1]*4)//5`, and `expandedArray` should be `expanded_array` for consistency), but otherwise it looks good.

> This is just confirming what was already in the documentation: http://picamera.readthedocs.io/en/release-1.10/recipes2.html

Although @6by9 got something wrong this time, as a general rule of thumb I would put a lot more stock in his words than my docs!

My limited understanding of the camera is cobbled together from forum posts, reading the raspistill/vid source, and several e-mails with 6by9. The firmware devs (of which 6by9 is one) know a great deal more about the camera than I do (or ever will, most likely) so if someone's got something wrong, your best bet is that I've got it wrong! Or to put it another way: the picamera docs are not gospel; they just reflect my (current) understanding of things :)

**Comment by waveform80** [comment]
I've been having a play with this and I'm really not sure the Bayer order's right in this PR. With a bog-standard V1 module the de-mosaic'd output is coming out with red and blue in the green channel and vice-versa. I'm going to switch output for a V2 module and see if that's different.

Also had a quick look at 6by9's modified dcraw code - doesn't look like it'd be too complex to incorporate some header parsing bits to handle flipped bayer orders so I might try and incorporate that while I'm playing with this stuff.

**Comment by waveform80** [comment]
Damn. Okay, the Bayer order's definitely different on the V2 (red and blue look absolutely fine on the V2 with the PR's code). Still, the PR's code is indeed notably faster than the original so it's probably time to nab some code from 6by9's dcraw and deal with the different Bayer orders.

**Comment by 6by9** [comment]
Just to warn you there have been a couple of reports of my dcraw not working against raws currently being captured, but I've not had a chance to investigate. https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=164753&p=1063473#p1063288

What I also ought to be adding is the offsets that would result if sensor_mode is set to force anything other than the 5 or 8MPix mode. The header parsing should give the right values to decode the image, but it's finding that header in the first place that is missing. The Broadcom approach was search the file for the @BRCM tag as there were any number of different sensors that we were using, but that's not the most efficient approach in a 10MB file.

**Comment by waveform80** [comment]
I must admit I didn't look too closely at the bits you'd added to dcraw: just grabbed the header structure and its offset. For still (full res) captures on the V1 and V2 modules I've now got something that seems to work nicely (and even takes into account the bayer order changing with flips). I'll have a play with different sensor modes and see what happens :)

**Comment by 6by9** [comment]
The awkward bit is how to find the header. 
dcraw currently has a hard coded seek from the end of either -10270208 bytes for V2, or -6404096 bytes for V1 sensors. (The useful structure is then (32+144=) 172 bytes on from that). Those are only valid for mode 2 or 3 off each sensor.
I either need to add a list of offsets to check, or do a genuine search for the ```@BRCM``` string.

**Comment by waveform80** [comment]
Okay, 92492b8c7b70f065e6d19270bab76294036b5ca0 and 3877f5f7326fc45a44b48267f81a2b3018e8ed6c finish this off nicely: PiBayerArray now supports:

* 3D and 2D output (3D remains default for backwards compat reasons)
* Correctly deals with different bayer orders of V1 and V2 modules
* Handles flipped captures correctly
* Handles all different sensor modes

**Comment by 6by9** [comment]
Thank you - you've just saved me working out all those offsets for dcraw :-)

**Comment by waveform80** [comment]
@6by9 No prob :)

I bashed off a quick script to flip between sensor modes, capture the bayer data and search backwards for BRCM in it: did notice a couple of weird things when running it. On the V2 module, flicking from sensor mode 1 directly to mode 2 failed, but switching from 1 to 0 to 2 worked (all the other transitions worked happily). On the V1 module, it didn't like something about sensor mode 3 (just got capture timeouts). I wasn't adjusting framerates and 30 is way outside the range of mode 3 (which is the <1fps mode), but then so is mode 2's max of 15 (which worked happily). In the end, I just assumed mode 3 would have the same offset as 2 given it's the same res. Don't know if any of that is worth looking into - I doubt there's many cases of people jumping around sensor modes like that - but I thought I should probably note it down somewhere in case it ever comes up!

**Comment by 6by9** [comment]
The timeout is set at max(4 frame times, 250ms), so 15fps will still easily fit inside that if you'd asked for 30. 1fps really doesn't!
Mode 3 will be identical to mode 2 in both cases.

Changing sensor mode dynamically wasn't something that was anticipated, but should work. The main use was to force an alternate configuration for a particular use case and therefore it was selected before enabling anything. If there are quirks then I can try to investigate, but won't be a high priority.

Now, of course, I need to find a 8 or 12 bit Bayer sensor to give you another challenge ;-)

**Pull request merged**
